In [1]:
import numpy as np
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.naive_bayes import GaussianNB

In [3]:
df = pd.read_csv("/content/winequality-white.csv", sep=";")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [4]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [5]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
df["quality"].unique()

array([6, 5, 7, 8, 4, 3, 9])

In [7]:
X = df[["fixed acidity", "volatile acidity", "citric acid", "residual sugar",
               "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH",
               "sulphates", "alcohol"]]
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
4893     11.2  
4894      9.6  
4895      9.4  
4896     12.8  
4897     11.8  

[4898 rows x 11 columns]

In [8]:
y = df[["quality"]]
y

quality
0           6
1           6
2           6
3           6
4           6
...       ...
4893        6
4894        5
4895        6
4896        7
4897        6

[4898 rows x 1 columns]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [14]:
# split into 2/3 test 1/3 train
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.33)

In [15]:
print("Number of data points x: %d" % len(X))
print("Number of classes: %d" % len(np.unique((y))))
print("Number of data points: %d" % len(y))

Number of data points x: 4898
Number of classes: 7
Number of data points: 4898


In [19]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")

Accuracy: 0.4826530612244898
Confusion Matrix:
[[  0   0   3   1   1   0]
 [  1   3  13   7   1   0]
 [  0   9 141 123  18   0]
 [  0   6 111 266  47   2]
 [  0   4  35  89  60   4]
 [  0   0   3  20   9   3]]
Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         5
           4       0.14      0.12      0.13        25
           5       0.46      0.48      0.47       291
           6       0.53      0.62      0.57       432
           7       0.44      0.31      0.37       192
           8       0.33      0.09      0.14        35

    accuracy                           0.48       980
   macro avg       0.32      0.27      0.28       980
weighted avg       0.47      0.48      0.47       980



/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [20]:
X_test[0:8]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
4656            6.0              0.29         0.41            10.8      0.048   
3659            5.4              0.53         0.16             2.7      0.036   
907             7.1              0.25         0.39             2.1      0.036   
4352            7.3              0.28         0.35             1.6      0.054   
3271            6.5              0.32         0.34             5.7      0.044   
4632            6.3              0.30         0.91             8.2      0.034   
2244            7.0              0.36         0.14            11.6      0.043   
1924            7.6              0.26         0.36             1.6      0.032   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
4656                 55.0                 149.0  0.99370  3.09       0.59   
3659                 34.0                 128.0  0.98856  3.20       0.53   
907                  30.0                 124.0  0.99080  3.28       0.43   
4352                 31.0                 148.0  0.99178  3.18       0.47   
3271                 27.0                  91.0  0.99184  3.28       0.60   
4632                 50.0                 199.0  0.99394  3.39       0.49   
2244                 35.0                 228.0  0.99770  3.13       0.51   
1924                  6.0                 106.0  0.99300  3.15       0.40   

        alcohol  
4656  10.966667  
3659  13.200000  
907   12.200000  
4352  10.700000  
3271  12.000000  
4632  11.700000  
2244   8.900000  
1924  10.400000

In [21]:
pred_7 = model.predict(X_test[0:8])
accuracy = accuracy_score(y_test[0:8], pred_7)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test[0:8], pred_7)}")
print(f"Classification Report:\n{classification_report(y_test[0:8], pred_7)}")

Accuracy: 0.25
Confusion Matrix:
[[1 0 0 0 0]
 [0 0 2 0 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 0 2 0 0]]
Classification Report:
              precision    recall  f1-score   support

           4       1.00      1.00      1.00         1
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           7       1.00      0.50      0.67         2
           8       0.00      0.00      0.00         2

    accuracy                           0.25         8
   macro avg       0.40      0.30      0.33         8
weighted avg       0.38      0.25      0.29         8



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
print(y_test[0:8].to_numpy().flatten())
print(pred_7)

[7 8 8 5 7 6 5 4]
[5 6 6 6 7 5 6 4]


In [13]:
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")

Accuracy: 0.4387755102040816
Confusion Matrix:
[[  2   0   1   2   0   0   0]
 [  1   6   8   6   4   0   0]
 [  7  14 155  79  36   0   0]
 [  4   5 117 144 159   2   1]
 [  0   0  22  41 123   6   0]
 [  0   1   2   5  27   0   0]
 [  0   0   0   0   0   0   0]]
Classification Report:
              precision    recall  f1-score   support

           3       0.14      0.40      0.21         5
           4       0.23      0.24      0.24        25
           5       0.51      0.53      0.52       291
           6       0.52      0.33      0.41       432
           7       0.35      0.64      0.45       192
           8       0.00      0.00      0.00        35
           9       0.00      0.00      0.00         0

    accuracy                           0.44       980
   macro avg       0.25      0.31      0.26       980
weighted avg       0.46      0.44      0.43       980



/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Recall and F-score are i